FROM node:23-alpine AS base

WORKDIR /app

RUN npm install --global nodemon vinxi

COPY package.json package-lock.json ./

RUN npm install

COPY . .

ENV PORT=3000

EXPOSE 3000

CMD ["sh", "-c", "npm run dev"]