services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tan-stack-start-full:latest
    container_name: tan-stack-start-full
    expose:
      - 3000
      # - 3001
    ports:
      - "3000:3000"
      # - "3001:3001"
    # volumes:
    # - ./apps/web/:/app/apps/web
    # - ./apps/docs/:/app/apps/docs
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - DOCS_PORT=${DOCS_PORT}
